dist: trusty

jobs:
  include:
    - stage: build docker image
      if: branch IN (develop, master) AND type IN (push, api)
      script:
      - if [[ "$TRAVIS_BRANCH" = "develop" ]]; then export DOCKER_TAG="staging"; else export DOCKER_TAG="production"; fi
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t travis-ci-build-appbuilder-agent .
      - docker images
      - docker tag travis-ci-build-appbuilder-agent "$DOCKER_USERNAME/appbuilder-agent:$DOCKER_TAG"
      - docker push "$DOCKER_USERNAME/appbuilder-agent:$DOCKER_TAG"