---

- name: Install Build Packages
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
    - git
    - cmake
    - libpng-dev
    - libpng16-16
    - libxml2-dev
    - pkg-config
    - ninja-build

- name: Clone xcbuild source
  git: repo=https://github.com/facebook/xcbuild depth=1 dest=/src/xcbuild

- name: Make xcbuild
  make: chdir=/src/xcbuild target=install

- name: Copy missing file
  shell: cp /src/xcbuild/build/liblinenoise.so /usr/lib

- name: Clean xcbuild source
  shell: rm -rf /src/xcbuild
