---
- name: Install bloom-app-maker native dependencies
  apt: 
    pkg:
      - build-essential
      - patch
      - zlib1g-dev
      - liblzma-dev
      - libmagickwand-dev
    state: latest

- name: Install Gems
  gem: name={{ item }} state=latest user_install=no
  with_items:
    - nokogiri
    - bundler
    - bundle
