---
- name: Configure dpkg to install i386 packages
  shell: dpkg --add-architecture i386

- name: Preseed dpkg for android-sdk-installer
  shell: echo android-sdk-installer android-sdk-installer/accepted-android-sdk-eula boolean true | debconf-set-selections -v

- name: Install packages
  apt: 
    pkg:
      - android-sdk-installer
      - app-builders
    state: latest 
    update_cache: yes

- name: Make directory for files
  file:
    path: /root/prime
    state: directory

- name: Copy files for priming build files
  copy: src={{ item }} dest=/root/prime/{{ item }}
  with_items:
    - keystore_prime.keystore
    - keystore_prime.txt
    - eng-web_usfm.zip
    - about.txt
    - ab-001-black-144.png
    - ab-001-black-72.png

- name: Prime gradle cache with build
  shell: HOME=/root scripture-app-builder -new -n web -p org.ebible -b /root/prime/eng-web_usfm.zip -ks /root/prime/keystore_prime.keystore -i /root/prime/keystore_prime.txt -a /root/prime/about.txt -ic /root/prime/ab-001-black-144.png -ic /root/prime/ab-001-black-72.png -fp build=/tmp/build
