---
- name: Update PATH
  blockinfile:
    dest: "/root/.bashrc"
    block: |
      export HOME=/root
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"
    marker: '# {mark} ANSIBLE MANAGED BLOCK - rbenv'

- name: Install rbenv dependencies
  apt: 
    pkg:
      - git
      - curl
      - libssl-dev
      - libreadline-dev
      - zlib1g-dev
      - autoconf
      - bison
      - build-essential
      - libyaml-dev
      - libreadline-dev
      - libncurses5-dev
      - libffi-dev
      - libgdbm-dev
    state: latest

- name: Install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /root/.rbenv

- name: Install ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /root/.rbenv/plugins/ruby-build

- name: Install ruby 3.3.4
  shell: |
    /root/.rbenv/bin/rbenv install 3.3.4
    /root/.rbenv/bin/rbenv global 3.3.4
  args:
    executable: /bin/bash
