---
- hosts: 127.0.0.1
  sudo: True
  gather_facts: False
  roles:
    - fastlane-supply
    - sil-software
    - scripture-app-builder
    - jenkins-swarm-client
  tasks:
    - name: Install other packages for the agent
      apt: pkg="{{ item }}" state=present
      with_items:
        - git
